# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

## Solution

In [1]:
#code here

import numpy as np

In [8]:
# arr = []

# for i in range(12):
#     arr.append(int(input("Enter the number: ")))

# arr = np.array(arr)

arr = np.arange(12)
print("Original Array:", arr)
arr = arr.reshape(3, 4)
print("\nReshaped Array\n", arr)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print("\nHorizontal Concat:", np.concatenate([arr1, arr2]))
print("\nVertical Concat:\n", np.vstack([arr1, arr2]))

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Horizontal Concat: [ 1  2  3  4  5  6  7  8  9 10]

Vertical Concat:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

## Solution

In [34]:
def classify_emails(emails):
    important = []
    promotions = []
    spam = []
    for email in emails:
        if any(keyword in email for keyword in spam_keywords):
            spam.append(email)

        elif any(keyword in email for keyword in promotions_keywords):
            promotions.append(email)
        
        elif any(keyword in email for keyword in important_keywords):
            important.append(email)

        # if email contains keywords from all the lists, tou spam ko priority milege phir promotions and then important kion k important mai spam k
        # keywords nae ho skte liken spam mai important k keywords ho skte hain
    
    return important, promotions, spam


important_keywords = ["Important", "Urgent", "Action Required", "Info Needed", "Information Needed" "Meeting", "Deadline", "Update", "Reminder"]
promotions_keywords = ["Promotions", "Deals", "Offers", "Sale", "Discount", "Coupon"]
spam_keywords = ["Lottery", "Free Money", "Bank Account", "Password", "OTP"]

emails = [
    "Hey, I wanted to remind you about the meeting tomorrow.",
    "Urgent: Your bank account needs an update.",
    "Urgent: You are required to update your information.",
    "Check out these amazing deals!",
    "Get free money now!",
    "Bank account information needed.",
    "You have won a lottery! Claim your prize now!",
    "Meeting tomorrow at 10 AM.",
    "Sale! Get 50% off on all items.",
    "Your password has expired. Click here to reset it.",
    "You won a lottery! Enter your OTP you received on your phone to claim your prize."
    "Your bank account has been locked. Click here to unlock it."
]

emails = [email.lower() for email in emails]

important_keywords = [keyword.lower() for keyword in important_keywords]
promotions_keywords = [keyword.lower() for keyword in promotions_keywords]
spam_keywords = [keyword.lower() for keyword in spam_keywords]


important, promotions, spam = classify_emails(emails)

important = [email.capitalize() for email in important]
promotions = [email.capitalize() for email in promotions]
spam = [email.capitalize() for email in spam]

print("Important emails:", important)
print("\n\nPromotions emails:", promotions)
print("\n\nSpam emails:", spam)

Important emails: ['Urgent: you are required to update your information.']


Promotions emails: ['Check out these amazing deals!', 'Sale! get 50% off on all items.']


Spam emails: ['Urgent: your bank account needs an update.', 'Get free money now!', 'Bank account information needed.', 'You have won a lottery! claim your prize now!', 'Your password has expired. click here to reset it.', 'You won a lottery! enter your otp you received on your phone to claim your prize.your bank account has been locked. click here to unlock it.']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


## Solution

In [65]:
#code here

dictionary = {
    "hello": "hola",
    "goodbye": "adios",
    "good bye": "adios",
    "yes": "si",
    "no": "no",
    "please": "por favor",
    "thank you": "gracias",
    "you're welcome": "de nada",
    "you are welcome": "de nada",
    "excuse me": "permiso",
    "i am sorry": "lo siento",
    "i'm sorry": "lo siento",
    "i don't understand": "no entiendo",
    "i don't know": "no se",
    "i do not understand": "no entiendo",
    "i do not know": "no se",
    "help": "ayuda",
    "computer": "computadora",
    "internet": "internet",
    "email": "correo electronico",
    "telephone": "telefono",
    "cell phone": "celular"
}

# Ask the user to input an English word.

while True:
    word = input("Enter an English word: ").lower()

    if word in dictionary:
        print(f"The Spanish translation for \"{word}\" is \"{dictionary[word]}\"")

    else:
        print(f"The translation for \"{word}\" is not available.")

    choice = input("Do you want to continue? (y/n) ").lower()
    if choice != "y":
        break

print("Goodbye!")

Enter an English word: hello
The Spanish translation for "hello" is "hola"
Do you want to continue? (y/n) y
Enter an English word: goodbye
The Spanish translation for "goodbye" is "adios"
Do you want to continue? (y/n) y
Enter an English word: i don't know
The Spanish translation for "i don't know" is "no se"
Do you want to continue? (y/n) n
Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

(Solution below the example)

In [3]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [2]:
# pip install networkx


In [1]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))


## Solution

In [66]:
import pandas as pd

In [67]:
df = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv', delimiter=',')
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [69]:
# Total global sales

print("Total global sales for all games in the dataset:", df['Global_Sales'].sum())

Total global sales for all games in the dataset: 8920.44


In [72]:
# Game with the highest global sales.

print ("The game with the highest global sales is: ")
df[df['Global_Sales'] == df['Global_Sales'].max()]

The game with the highest global sales is: 


Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

In [75]:
# Average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).

print("Average sales for each region:\n")
print("NA_Sales:", df['NA_Sales'].mean())
print("EU_Sales:", df['EU_Sales'].mean())
print("JP_Sales:", df['JP_Sales'].mean())
print("Other_Sales:", df['Other_Sales'].mean())

Average sales for each region:

NA_Sales: 0.26466742981082064
EU_Sales: 0.14665200626581515
JP_Sales: 0.077781660441017
Other_Sales: 0.0480630196409206


In [82]:
# Top 5 most popular game genres based on global sales.

print("Top 5 most popular game genres based on global sales:\n\n")
df.groupby('Genre')['Global_Sales'].sum().nlargest(5)      
# nlargest() function aik column ki otne top values return karta hai jitne ap parameter mei pass karte hain

Top 5 most popular game genres based on global sales:




Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [96]:
# Total sales for each genre in each region and find the most popular genre in North America (NA_Sales).

print("Total sales for each genre in each region:\n")
print(df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum())
print("\n\nMost popular genre in North America (NA_Sales):", df.groupby('Genre')['NA_Sales'].sum().idxmax())

Total sales for each genre in each region:

              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


Most popular genre in North America (NA_Sales): Action


In [97]:
# Last 10 rows.

df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [98]:
# Top 3 gaming platforms with the highest global sales.

df.groupby('Platform')['Global_Sales'].sum().nlargest(3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [111]:
# Market share (percentage of global sales) for each genre.

print("Market share (percentage of global sales) for each genre:\n")
(df.groupby('Genre')['Global_Sales'].sum() / (df['Global_Sales'].sum()) * 100)

Market share (percentage of global sales) for each genre:



Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [115]:
# Correlation coefficient between NA_Sales and EU_Sales. (.corr function)

print("Correlation coefficient between NA_Sales and EU_Sales:", df['NA_Sales'].corr(df['EU_Sales']))

Correlation coefficient between NA_Sales and EU_Sales: 0.7677267483702562
